moveit_controller_manager: moveit_ros_control_interface/Ros2ControlMultiManager

controller_names:
  - /panda/joint_trajectory_controller
  - /robotiq/robotiq_gripper_controller

/panda/joint_trajectory_controller:
  default: true
  type: FollowJointTrajectory
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  action_ns: /panda/joint_trajectory_controller/follow_joint_trajectory

/robotiq/robotiq_gripper_controller:
  type: GripperCommand
  joints:
    - robotiq_85_left_knuckle_joint
  action_ns: /robotiq/robotiq_gripper_controller/gripper_cmd
