/panda/controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gravity_compensation_example_controller:
      type: franka_example_controllers/GravityCompensationExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

/panda/joint_state_broadcaster:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    interfaces:
      - position
      - velocity
      - effort

/panda/joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    gains:
      panda_joint1: { p: 2600., d: 30., i: 0., i_clamp: 1. }
      panda_joint2: { p: 2600., d: 30., i: 0., i_clamp: 1. }
      panda_joint3: { p: 2600., d: 30., i: 0., i_clamp: 1. }
      panda_joint4: { p: 2600., d: 30., i: 0., i_clamp: 1. }
      panda_joint5: { p: 2250., d: 10., i: 0., i_clamp: 1. }
      panda_joint6: { p: 2150., d: 10., i: 0., i_clamp: 1. }
      panda_joint7: { p: 250., d: 5., i: 0., i_clamp: 1. }


/panda/joint_impedance_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 500.0
      - 100.0
      - 100.0
    d_gains:
      - 40.0
      - 40.0
      - 100.0
      - 400.0
      - 20.0
      - 20.0
      - 10.0