/robotiq/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    robotiq_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

/robotiq/robotiq_state_broadcaster:
  ros__parameters:
    joints: 
      - robotiq_85_left_knuckle_joint
    interfaces:
      - position
      - velocity

/robotiq/robotiq_gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: 'robotiq_85_left_knuckle_joint'
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
